import { Complish } from "./cyk.js";

const sentences = [
    'The woman eats the fish with the chopsticks before eating the fish with a fork',
    "To draw giving, do nothing",
    'The woman eats a fish with the chopsticks before eating the fish with a fork',
    "To draw giving a number to a number, do nothing",
    "Say",
    "To give a percentage to a number do nothing",
    "To say, give 10% to 21, give 10% to 21",
    "Say",
    "Give 3% to 2",
    "A numeric buggy drives a number",
    "To draw a vertical percentage by a horizontal percentage, draw",
    "To draw, give the percentage which 5 gave to 7",
    "Before drawing a number, give the number",
    "Draw a number before giving the number",
    "To give something to anything , do nothing",
    "A wheel is a number",
    "A car is many wheel, several percentage",
    "To give asap a numeric rank to just a percentage boldly,  do nothing",
    "Numeric horses are a charismatic number and a car",
    "Toby MacGuire is a charismatic number and a car",
    "A car is a textual make, a textual model, and a numeric year",
    //"Foospace begins here",
    "A car is a textual make, a textual model, and a numeric year",
    "To give a numeric rank to a percentage, do nothing",
    "To throw a numeric rank at a percentage, do nothing",
    "To give a numeric rank to a percentage, know the percentage, then know 12%",
    "To give a percentage a numeric rank a position, do nothing",
    "To give a percentage a numeric rank, do nothing",
    "A numeric power level gives a numeric rank to a percentage",
    "A numeric charisma is a numeric rank and a percentage",
    "A buggy is many wheel and a numeric rank",
    "Someone knows many someone",
    "To know a percentage, know the percentage",
    "To draw a percentage toward a percentage, do nothing",
    "To draw, say \"Hello World!\"",
    "To say a text, say the text",
    //"To draw twice, say "Hello""World""!"",
    //"To draw thrice, say """Hello"" world!"",
    //"To say nothing, say """,
    "To say trouble, give 10% to 21, give anything to anything",
    "To draw giving a number to a number, do nothing",
    "To give a number to a number, do nothing",
    "To know, draw",
    "To do: say nothing",
    "To choose, know the percentage which was given to 5",
    "To choose, know the percentage which 5 gave to 7",
    "To choose, know the percentage to which 5 gave 7",
    "The Corvette is a car",
    "The car is many number",
    "To draw giving, do nothing",
    "To draw choosing, do nothing",
    "To throw, draw giving 3 to 2",
    "To weave, draw giving a number to 2",
    "Giving a number to a number is an activity",
    "When a function reads a variable, change the variable to anything before invoking the function",
    'The woman eats the fish with the chopsticks before eating the fish with a fork',
];

document.getElementById("main")!.innerHTML = Complish(sentences);
